name: Java Learning

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Passo 1 - Checkout
        uses: actions/checkout@v4

      - name: Passo 2 - Intalar JDK
        uses: action/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Passo3 - Executar Lint
        run: mvn checkstyle: check

      - name: Passo3.5 - Build do projeto 
        run: mvn package - DskipTests

      - name: Passo4 - Upload do Resultado
        uses: actions/upload-artifact@v4
        with:
          name: meu-projeto
          path: target/
